[package]
name = "webserver"
version = "0.1.0"
authors = ["tom <bla@thecout.com>"]

[dependencies]
tiny_http = "0.5"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
compiletest_rs = "0.3"
serde_bytes = "0.10"
